export const FETCH_ACTIVITY = "FETCH_ACTIVITY";
export const FETCH_ACTIVITY_BY_SLUG = "FETCH_ACTIVITY_BY_SLUG";
export const FETCH_RELATED_ACTIVITY = "FETCH_RELATED_ACTIVITY";
export const SET_META_DATA = "SET_META_DATA";
export const APPEND_TO_ACTIVITY = "APPEND_TO_ACTIVITY";