export const FETCH_RESEARCH = "FETCH_RESEARCH";
export const FETCH_RESEARCH_BY_SLUG = "FETCH_RESEARCH_BY_SLUG";
export const SET_META_DATA = "SET_META_DATA";
export const APPEND_TO_RESEARCH = "APPEND_TO_RESEARCH";
