export const FETCH_ARTICLES = "FETCH_ARTICLES";
export const FETCH_ARTICLES_BY_SLUG = "FETCH_ARTICLES_BY_SLUG";
export const SET_META_DATA = "SET_META_DATA";
export const APPEND_TO_ARTICLE = "APPEND_TO_ARTICLE";
